### ISSUE TITLE
Hash for entire dataframe

### ISSUE THREAD

**Issue by mkleinbort-ic** [ion-elgreco/polars-hash#1]
Hi, does Polars-hash support hashing entire dataframes? Something that can serve the purpose of `__hash__` for the purposes of caching computations.

**Comment by ion-elgreco** [comment]
Hi @mkleinbort-ic, no it's only on Series level. What are you trying to achieve by caching the computations?

**Comment by mkleinbort** [comment]
It's to support caching of functions that take in a data frame as an input. This is very common - see streamlit as an example.

**Comment by ion-elgreco** [comment]
Do you requires stability of the hash across polars versions?

**Comment by mkleinbort-ic** [comment]
Stability is always nice, but no, not necessary - a Polars update probably merits invalidating caches.

**Comment by ion-elgreco** [comment]
Closing this as not planned
