### ISSUE TITLE
`.from_coords()` not actually converting lat/lon to geohashes :(

### ISSUE THREAD

**Issue by ThomasMAhern** [ion-elgreco/polars-hash#13]
I had an inkling that it wasn't working, but figured it was something I was doing wrong. I just finally tested it.

```python
(pl.from_dict({"longitude": [90.6623,-120.6623], "latitude": [40.3003, 35.3003]})
 .with_columns(geohash = pl.struct(['latitude', 'longitude']))
 .with_columns(plh.col('geohash').geohash.from_coords())
)
```

This outputs the same geohash despite two very different coordinates.

**Comment by ion-elgreco** [comment]
@ThomasMAhern I found the pitfall the length of the series of len is 1, I need some time to figure out how to fix it though: )

In the meantime do this:

(pl.from_dict({"longitude": [90.6623,-120.6623], "latitude": [40.3003, 35.3003]})
 .with_columns(geohash = pl.struct(['latitude', 'longitude']), hash_length = pl.lit(12))
 .with_columns(plh.col('geohash').geohash.from_coords("hash_length"))
)

**Comment by ion-elgreco** [comment]
@ThomasMAhern check out v0.4.1 it includes the fix and will be available in couple minutes on PyPi

**Comment by ThomasMAhern** [comment]
So fast! Was gonna test it out! But even that fix was manageable, since I'm probably one of the only ones that uses it! Thank you!
